version: '3.1'
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cloud_db
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "4321:8080"